### ISSUE TITLE
Can this code be used as (supervised problem)  to predict new labels?

### ISSUE THREAD

**Issue by nisnab** [yankeesrules/C2AE#1]
I would like to know if it is possible to predict new labels with this algorithm. 
Sorry for any inconvenience caused.

**Comment by chihkuanyeh** [comment]
Hi, I don't quite understand the question. Do you mean new labels as in the zero-shot setting?

**Comment by chihkuanyeh** [comment]
@Nisnab can you illustrate what does new labels mean in this context?
